name: Deploy App B

on:
  push:
    branches:
      - main
    paths:
      - "apps/app-b/**"
      - "shared/**"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-shared.yaml
    with:
      app_name: app-b
      working_directory: apps/app-b
      environment: playground
